### ISSUE TITLE
Cannot find name 'Title'

### ISSUE THREAD

**Issue by laroby** [pgvlas/angular-dynamic-page-titles#1]
Hello,
i have followed https://medium.com/@p.gvlas/dynamic-page-titles-in-angular-518a2b8d03d2 and moreover i have double check on this demo, but when i have compiled i have received the followin error...
src/app/app.module.ts(331,3): error TS2304: Cannot find name 'Title'.
Thanks a lot for yout time
R.

**Comment by laroby** [comment]
thanks a lot for your answer. In app.module.ts i have already set title such as import, this was the problem for running the application. Anyway it still take a random title and not what i set in app-routing.module.ts . I'm wondering why. Thanks

**Comment by pgvlas** [comment]
How do you set title in your component? Is it setting random strings from your app-routing `data` properties?

**Comment by laroby** [comment]
localhost:4200/about, localhost:4200/how it works,most of them exept one in the tag label, in the title page nothing. In my app-routing.module.ts:
 export const routes: Routes = [{
    path: '',
    component: HomeComponent,
    data: { title: 'Home' }}, 
  {

thanks
